name: livekit_voice_app
description: "A Flutter LiveKit voice chat application with Keycloak authentication."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  livekit_client: ^2.5.2
  http: ^1.2.2
  keycloak_wrapper: ^1.4.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2
  logger: ^2.4.0
  google_fonts: ^6.2.1
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  just_audio: ^0.9.40
  grpc: ^4.0.1
  protobuf: ^3.1.0
  wireguard_flutter: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/voice_button.json
    - assets/lottie/login-button.json
    - assets/lottie/lock-button.json
    - assets/icon/app_icon.png
    

flutter_icons:
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
