name: livekit_voice_app
description: "A Flutter LiveKit voice chat application with Keycloak authentication."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  livekit_client: ^2.3.6
  http: ^1.2.2
  keycloak_wrapper: ^1.4.0
  permission_handler: ^11.3.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/voice_button.json
